apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seedbox
spec:
  destination:
    name: microk8s
    namespace: seedbox
  source:
    path: vps-evo/argo/seedbox
    repoURL: "https://github.com/fabricepipart/build-infra"
    targetRevision: HEAD
    directory:
      recurse: true
  project: seedbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
