apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: seedbox
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: networking.k8s.io
      kind: Ingress
  destinations:
    - name: microk8s
      namespace: seedbox
      server: "*"
    - name: in-cluster
      namespace: argocd
      server: "*"
  sourceRepos:
    - https://github.com/fabricepipart/build-infra
