apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: seedbox
  namespace: argocd
spec:
  destinations:
    - name: microk8s
      namespace: seedbox
      server: "*"
    - name: in-cluster
      namespace: argocd
      server: "*"
  sourceRepos:
    - https://github.com/fabricepipart/build-infra
